config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/argoeu/argo-web-api:
      branch: devel
      repo: https://github.com/argoeu/argo-web-api
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/argoeu/argo-web-api git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-cerulean-buffalo.sh
        container: qc.acc_foggy-grey-urchin
  QC.Doc:
    repos:
      github.com/argoeu/argo-web-api find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-magenta-chin.sh
        container: qc.doc_zippy-ruby-lobster
      github.com/argoeu/argo-web-api git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-scarlet-bandicoot.sh
        container: qc.doc_goopy-violet-panda
      github.com/argoeu/argo-web-api markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-lime-caterpillar.sh
        container: qc.doc_foggy-myrtle-spaniel
  QC.Lic:
    repos:
      github.com/argoeu/argo-web-api licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-azure-javanese.sh
        container: qc.lic_nippy-salmon-akita
  QC.Met:
    repos:
      github.com/argoeu/argo-web-api cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-periwinkle-goose.sh
        container: qc.met_ready-magnolia-fowl
  QC.Sec:
    repos:
      github.com/argoeu/argo-web-api bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-goldenrod-greyhound.sh
        container: qc.sec_muzzy-beige-mau
      github.com/argoeu/argo-web-api gosec:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-xanthic-monkey.sh
        container: qc.sec_gimpy-auburn-dragon
  QC.Sty:
    repos:
      github.com/argoeu/argo-web-api flake8:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-cerise-newfoundland.sh
        container: qc.sty_chummy-brass-okapi
      github.com/argoeu/argo-web-api jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-cornflower-lemming.sh
        container: qc.sty_skimpy-denim-mongrel
      github.com/argoeu/argo-web-api staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-purple-whale.sh
        container: qc.sty_stealthy-fuchsia-crane
  QC.Ver:
    repos:
      github.com/argoeu/argo-web-api get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-buff-cat.sh
        container: qc.ver_pretty-viridian-lobster
timeout: 5400
