config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/argoeu/argo-web-api:
      branch: devel
      repo: https://github.com/argoeu/argo-web-api
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/argoeu/argo-web-api git:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-harlequin-centipede.sh
        container: qc.acc_gummy-vermilion-donkey
  QC.Doc:
    repos:
      github.com/argoeu/argo-web-api find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-seashell-donkey.sh
        container: qc.doc_lumpy-peach-wolf
      github.com/argoeu/argo-web-api git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-gold-okapi.sh
        container: qc.doc_skanky-celadon-sheepdog
      github.com/argoeu/argo-web-api markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-pink-heron.sh
        container: qc.doc_flimsy-blue-grasshopper
  QC.Lic:
    repos:
      github.com/argoeu/argo-web-api licensee:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-amber-chinchilla.sh
        container: qc.lic_dorky-xanthic-gopher
  QC.Sec:
    repos:
      github.com/argoeu/argo-web-api bandit:
        commands:
        - /usr/bin/env sh .sqa/script.silly-olive-hare.sh
        container: qc.sec_fuzzy-cerise-beetle
      github.com/argoeu/argo-web-api gosec:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-cerulean-tamarin.sh
        container: qc.sec_stealthy-fuchsia-greyhound
  QC.Sty:
    repos:
      github.com/argoeu/argo-web-api flake8:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-turquoise-armadillo.sh
        container: qc.sty_homey-plum-sparrow
      github.com/argoeu/argo-web-api jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-goldenrod-mandrill.sh
        container: qc.sty_gamy-ultramarine-bobcat
      github.com/argoeu/argo-web-api staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-bistre-jellyfish.sh
        container: qc.sty_sickly-orchid-olm
  QC.Ver:
    repos:
      github.com/argoeu/argo-web-api get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-puce-chihuahua.sh
        container: qc.ver_stinky-olive-hare
timeout: 5400
