config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/argoeu/argo-web-api:
      branch: devel
      repo: https://github.com/argoeu/argo-web-api
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/argoeu/argo-web-api git:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-beige-jackal.sh
        container: qc.acc_seedy-ruby-bloodhound
  QC.Doc:
    repos:
      github.com/argoeu/argo-web-api find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-bistre-dachsbracke.sh
        container: qc.doc_sloppy-scarlet-tzu
      github.com/argoeu/argo-web-api git:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-maroon-chinook.sh
        container: qc.doc_flimsy-copper-capuchin
      github.com/argoeu/argo-web-api markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-bronze-kingfisher.sh
        container: qc.doc_gloppy-charcoal-newt
  QC.Lic:
    repos:
      github.com/argoeu/argo-web-api licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-peach-rhinoceros.sh
        container: qc.lic_lousy-thistle-orangutan
  QC.Sec:
    repos:
      github.com/argoeu/argo-web-api bandit:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-cardinal-caiman.sh
        container: qc.sec_woozy-smalt-collie
      github.com/argoeu/argo-web-api gosec:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-goldenrod-manatee.sh
        container: qc.sec_gamy-vermilion-dragonfly
  QC.Sty:
    repos:
      github.com/argoeu/argo-web-api flake8:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-magnolia-indri.sh
        container: qc.sty_crappy-scarlet-rat
      github.com/argoeu/argo-web-api jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-brass-sparrow.sh
        container: qc.sty_stuffy-fuchsia-cattle
      github.com/argoeu/argo-web-api staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-amber-bee.sh
        container: qc.sty_crappy-brown-stingray
  QC.Ver:
    repos:
      github.com/argoeu/argo-web-api get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-black-spider.sh
        container: qc.ver_messy-white-otter
timeout: 5400
